### PR TITLE
[Fix]: Space not there issue

### PR DESCRIPTION
**Pull request by muskankhedia**
Fixes:https://github.com/coding-blocks/codingblocks.com/issues/446

Replaces the "**.**" if present in the string with the  " "

### CODE REVIEW

**Comment by muskankhedia** [comment]
@witty123 Please have a look and suggest if any changes required.

**Comment by championswimmer** [comment]
why not replace the category name properly in the resources repository ?

**Comment by muskankhedia** [comment]
I thought for the same and after searching a lot, I reached up to the file from which the data is fetched and has typo error, but not confirm will it make the changes in the website as there is no static site generator to generate and deploy the changes. But was confirm with this idea, and so implemented it.

@championswimmer Should I change in the .md file instead?

**Comment by muskankhedia** [comment]
@championswimmer Pls review the PR.

**Pull request closed without merging**
